# Generated by Django 5.2.7 on 2025-11-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_allow_delete_products_with_completed_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Opciono', max_length=254, null=True),
        ),
    ]
