# Generated by Django 5.2.8 on 2025-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_variant_independent_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Osnovna cena ove varijante', max_digits=10),
        ),
    ]
