# Generated by Django 5.2.8 on 2025-12-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_add_sold_by_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Količina (može biti decimalna za proizvode po metraži)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_by_length',
            field=models.BooleanField(default=False, help_text='Proizvod se prodaje po metraži'),
        ),
    ]
