# Generated by Django 6.0 on 2025-12-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_add_updated_at_to_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., JoilArt, Jeep Commerce', max_length=100, unique=True)),
                ('url', models.URLField(help_text='Base URL of the competitor site')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable scraping for this site')),
                ('scrape_interval_hours', models.IntegerField(default=24, help_text='How often to scrape (in hours)')),
                ('crawl_delay_seconds', models.IntegerField(default=3, help_text='Delay between requests (respect robots.txt)')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konkurentski sajt',
                'verbose_name_plural': 'Konkurentski sajtovi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text="Product ID on competitor's site", max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current price in RSD', max_digits=10)),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True)),
                ('product_url', models.URLField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('in_stock', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if product no longer appears on competitor site')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_products', to='shop.competitorsite')),
            ],
            options={
                'verbose_name': 'Scraped proizvod',
                'verbose_name_plural': 'Scraped proizvodi',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='shop.scrapedproduct')),
            ],
            options={
                'verbose_name': 'Istorija cena',
                'verbose_name_plural': 'Istorije cena',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('products_found', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('products_new', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='shop.competitorsite')),
            ],
            options={
                'verbose_name': 'Scrape log',
                'verbose_name_plural': 'Scrape logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scrapedproduct',
            index=models.Index(fields=['site', 'external_id'], name='shop_scrape_site_id_227a87_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedproduct',
            index=models.Index(fields=['category'], name='shop_scrape_categor_897310_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedproduct',
            index=models.Index(fields=['on_sale'], name='shop_scrape_on_sale_ef717d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapedproduct',
            unique_together={('site', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', '-recorded_at'], name='shop_priceh_product_a6fc41_idx'),
        ),
    ]
