# Generated by Django 6.0 on 2025-12-22 10:06

from django.db import migrations


def add_competitor_sites(apps, schema_editor):
    """Dodaj inicijalne konkurentske sajtove"""
    CompetitorSite = apps.get_model('shop', 'CompetitorSite')

    sites = [
        {
            'name': 'joilart',
            'url': 'https://joilart.com',
            'is_active': True,
            'scrape_interval_hours': 24,
        },
        {
            'name': 'Hanan',
            'url': 'https://hanan.rs',
            'is_active': True,
            'scrape_interval_hours': 24,
        },
        {
            'name': 'Velog',
            'url': 'https://velog.rs',
            'is_active': False,  # Deaktiviran
            'scrape_interval_hours': 24,
        },
        {
            'name': 'JeepCommerce',
            'url': 'https://jeepcommerce.rs',
            'is_active': False,  # Deaktiviran
            'scrape_interval_hours': 24,
        },
        {
            'name': 'IronWorks',
            'url': 'https://ironworks.rs',
            'is_active': False,  # Deaktiviran
            'scrape_interval_hours': 24,
        },
    ]

    for site_data in sites:
        CompetitorSite.objects.get_or_create(
            name=site_data['name'],
            defaults={
                'url': site_data['url'],
                'is_active': site_data['is_active'],
                'scrape_interval_hours': site_data['scrape_interval_hours'],
            }
        )


def remove_competitor_sites(apps, schema_editor):
    """Ukloni konkurentske sajtove (reverse migration)"""
    CompetitorSite = apps.get_model('shop', 'CompetitorSite')
    site_names = ['joilart', 'Hanan', 'Velog', 'JeepCommerce', 'IronWorks']
    CompetitorSite.objects.filter(name__in=site_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_add_scraping_models'),
    ]

    operations = [
        migrations.RunPython(add_competitor_sites, remove_competitor_sites),
    ]
