# Generated by Django 6.0 on 2025-12-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_add_initial_competitor_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL (auto-generiše se iz naziva)', max_length=250, null=True),
        ),
    ]
