# Generated by Django 6.0 on 2025-12-24 10:11

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Generiše slug-ove za sve postojeće proizvode"""
    Product = apps.get_model('shop', 'Product')

    # Transliteracija ćiriličnih karaktera u latinične
    cyrillic_map = {
        'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'ђ': 'dj', 'е': 'e', 'ж': 'z',
        'з': 'z', 'и': 'i', 'ј': 'j', 'к': 'k', 'л': 'l', 'љ': 'lj', 'м': 'm', 'н': 'n',
        'њ': 'nj', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'ћ': 'c', 'у': 'u',
        'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'c', 'џ': 'dz', 'ш': 's',
        'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Ђ': 'Dj', 'Е': 'E', 'Ж': 'Z',
        'З': 'Z', 'И': 'I', 'Ј': 'J', 'К': 'K', 'Л': 'L', 'Љ': 'Lj', 'М': 'M', 'Н': 'N',
        'Њ': 'Nj', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'Ћ': 'C', 'У': 'U',
        'Ф': 'F', 'Х': 'H', 'Ц': 'C', 'Ч': 'C', 'Џ': 'Dz', 'Ш': 'S'
    }

    for product in Product.objects.all():
        if not product.slug:
            # Transliteriši ćirilicu u latinicu
            transliterated = ''.join(cyrillic_map.get(char, char) for char in product.name)

            # Slugify transliterisani tekst
            base_slug = slugify(transliterated)

            # Proveri jedinstvenost slug-a
            unique_slug = base_slug
            num = 1
            while Product.objects.filter(slug=unique_slug).exists():
                unique_slug = f'{base_slug}-{num}'
                num += 1

            product.slug = unique_slug
            product.save(update_fields=['slug'])


def reverse_slugs(apps, schema_editor):
    """Uklanja slug-ove (za rollback)"""
    Product = apps.get_model('shop', 'Product')
    Product.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, reverse_slugs),
    ]
