# Generated by Django 6.0 on 2025-12-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_populate_product_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, blank=True, help_text='SEO-friendly URL (auto-generiše se iz naziva)'),
        ),
    ]
