# Generated by Django 6.0 on 2025-01-05

from django.db import migrations, models
import re


def populate_dimension_values(apps, schema_editor):
    """Popunjava dimension_value za sve postojeće varijante"""
    ProductVariant = apps.get_model('shop', 'ProductVariant')

    for variant in ProductVariant.objects.all():
        # Ekstraktuj prvi broj iz imena
        match = re.search(r'(\d+)', variant.name)
        if match:
            variant.dimension_value = int(match.group(1))
        else:
            variant.dimension_value = 0
        variant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_make_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='dimension_value',
            field=models.IntegerField(default=0, help_text="Numerička vrednost za sortiranje (npr. 20 za '20x20', 100 za '100x100')"),
        ),
        migrations.RunPython(populate_dimension_values, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['dimension_value', 'name']},
        ),
    ]
